import { Eye, Route, Cpu, MessageSquare, ArrowRight } from 'lucide-react'
import { mono, pillStyle } from '../theme.js'

// The actual data-flow contract from core/interfaces.py, wired together in
// member4_llm_rag/orchestrator.py: Perception and Planning both feed the
// Policy each tick; Mission refreshes periodically (every 30 ticks in
// orchestrator.py) and reshapes Planning's reward, not the tick loop itself.
//
// `activeModule` picks which stage is "driving" the currently displayed
// run: 'planning' for the A*/MCTS tile-grid replay, 'policy' for the
// trained PPO agent's native-environment replay. Perception and Mission
// are implemented but don't independently drive either replay yet.
const STAGE_DEFS = [
  { icon: Eye, n: '01', name: 'Perception', tag: 'CNN + LSTM', key: 'perception' },
  { icon: Route, n: '02', name: 'Planning', tag: 'A* + MCTS', key: 'planning' },
  { icon: Cpu, n: '03', name: 'Policy', tag: 'PPO / DQN', key: 'policy' },
  { icon: MessageSquare, n: '04', name: 'Mission', tag: 'SLM + RAG', key: 'mission' },
]

function Node({ stage, active }) {
  const { icon: Icon } = stage
  return (
    <div style={{
      flex: '1 1 0', minWidth: 130,
      border: `1px solid ${active ? 'var(--live)' : 'var(--line)'}`,
      borderRadius: 8,
      background: active ? 'var(--live-dim)' : 'var(--panel)',
      padding: '12px 14px',
      boxShadow: active ? '0 0 16px rgba(69,224,196,0.18)' : 'none',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <Icon size={15} color={active ? 'var(--live)' : 'var(--text-dim)'} />
        <span style={{ fontFamily: mono, fontSize: 9, color: 'var(--pending)' }}>{stage.n}</span>
        <span style={{ fontFamily: 'var(--sans)', fontWeight: 600, fontSize: 13 }}>{stage.name}</span>
      </div>
      <div style={{ fontFamily: mono, fontSize: 10, color: active ? 'var(--live)' : 'var(--text-dim)', marginBottom: 8 }}>
        {stage.tag}
      </div>
      <span style={pillStyle(active ? 'live' : 'pending')}>
        {active ? 'DRIVING THIS RUN' : 'IMPLEMENTED'}
      </span>
    </div>
  )
}

export default function PipelineFlow({ activeModule = 'planning' }) {
  const caption = activeModule === 'policy'
    ? 'This replay is generated entirely by the trained PPO policy (Member 3) acting greedily in its native continuous-physics training environment — no planner or perception in the loop for this run.'
    : "Perception + Planning feed Policy every tick; Mission re-interprets the goal every 30 ticks and reshapes reward rather than acting directly. All 4 are implemented — this replay was generated by Planning's A*/MCTS search alone."

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'stretch', gap: 6, flexWrap: 'wrap' }}>
        {STAGE_DEFS.map((s, i) => (
          <div key={s.n} style={{ display: 'flex', alignItems: 'center', gap: 6, flex: '1 1 0', minWidth: 130 }}>
            <Node stage={s} active={s.key === activeModule} />
            {i < STAGE_DEFS.length - 1 && (
              <ArrowRight size={14} color="var(--pending)" style={{ flexShrink: 0 }} />
            )}
          </div>
        ))}
      </div>
      <p style={{
        margin: '10px 0 0', fontFamily: mono, fontSize: 10.5, color: 'var(--text-dim)', lineHeight: 1.6,
      }}>
        {caption}
      </p>
    </div>
  )
}
