import { Eye, Route, Cpu, MessageSquare, ArrowRight } from 'lucide-react'
import { mono, pillStyle } from '../theme.js'

// The actual data-flow contract from core/interfaces.py, wired together in
// member4_llm_rag/orchestrator.py: Perception and Planning both feed the
// Policy each tick; Mission refreshes periodically (every 30 ticks in
// orchestrator.py) and reshapes Planning's reward, not the tick loop itself.
const STAGES = [
  { icon: Eye, n: '01', name: 'Perception', tag: 'CNN + LSTM', active: false },
  { icon: Route, n: '02', name: 'Planning', tag: 'A* + MCTS', active: true },
  { icon: Cpu, n: '03', name: 'Policy', tag: 'PPO / DQN', active: false },
  { icon: MessageSquare, n: '04', name: 'Mission', tag: 'SLM + RAG', active: false },
]

function Node({ stage }) {
  const { icon: Icon } = stage
  return (
    <div style={{
      flex: '1 1 0', minWidth: 130,
      border: `1px solid ${stage.active ? 'var(--live)' : 'var(--line)'}`,
      borderRadius: 8,
      background: stage.active ? 'var(--live-dim)' : 'var(--panel)',
      padding: '12px 14px',
      boxShadow: stage.active ? '0 0 16px rgba(69,224,196,0.18)' : 'none',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <Icon size={15} color={stage.active ? 'var(--live)' : 'var(--text-dim)'} />
        <span style={{ fontFamily: mono, fontSize: 9, color: 'var(--pending)' }}>{stage.n}</span>
        <span style={{ fontFamily: 'var(--sans)', fontWeight: 600, fontSize: 13 }}>{stage.name}</span>
      </div>
      <div style={{ fontFamily: mono, fontSize: 10, color: stage.active ? 'var(--live)' : 'var(--text-dim)', marginBottom: 8 }}>
        {stage.tag}
      </div>
      <span style={pillStyle(stage.active ? 'live' : 'pending')}>
        {stage.active ? 'DRIVING THIS RUN' : 'IMPLEMENTED'}
      </span>
    </div>
  )
}

export default function PipelineFlow() {
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'stretch', gap: 6, flexWrap: 'wrap' }}>
        {STAGES.map((s, i) => (
          <div key={s.n} style={{ display: 'flex', alignItems: 'center', gap: 6, flex: '1 1 0', minWidth: 130 }}>
            <Node stage={s} />
            {i < STAGES.length - 1 && (
              <ArrowRight size={14} color="var(--pending)" style={{ flexShrink: 0 }} />
            )}
          </div>
        ))}
      </div>
      <p style={{
        margin: '10px 0 0', fontFamily: mono, fontSize: 10.5, color: 'var(--text-dim)', lineHeight: 1.6,
      }}>
        Perception + Planning feed Policy every tick; Mission re-interprets the goal every 30 ticks and
        reshapes reward rather than acting directly. All 4 are implemented — this replay was generated by
        Planning's A*/MCTS search alone.
      </p>
    </div>
  )
}
